#
# efi-ia64.mk
# Peter Jones, 2019-11-13 14:27
#
ifeq ($(EFI_ARCH),ia64)

EFI_ARCH_CFLAGS := -mfixed-range=f32-f127 -m64 \
		   -DPAGE_SIZE=4096 -DPAGE_SHIFT=12
EFI_ARCH_LDFLAGS :=
EFI_ARCH_SUFFIX := ia64
EFI_ARCH_SUFFIX_UPPER := IA64
# XXX I have no idea if this is right
EFI_ARCH_TIMESTAMP_LOCATION := 136

export EFI_ARCH_CFLAGS EFI_ARCH_CPPFLAGS EFI_ARCH_LDFLAGS
export EFI_ARCH_FORMAT EFI_ARCH_SUBSYSTEM EFI_ARCH_SUFFIX EFI_ARCH_SUFFIX_UPPER
export EFI_ARCH_TIMESTAMP_LOCATION EFI_ARCH_3264
export EFI_ARCH_CLANG_BUGS EFI_ARCH_CAN_DISABLE_AVX
endif
