#
# efi-riscv64.mk
# Peter Jones, 2019-11-13 14:27
#
ifeq ($(EFI_ARCH),riscv64)

EFI_ARCH_3264 :=
EFI_ARCH_SUBSYSTEM := 0xa

EFI_ARCH_CFLAGS := -DPAGE_SIZE=4096 -DPAGE_SHIFT=12 \
		   -march=rv64imafdc -msmall-data-limit=0 -mcmodel=medany \
		   -mabi=lp64 -fpack-struct=8
# I'm not sure why we need EFI_SUBSYSTEM defined here on riscv but not on aa64
EFI_ARCH_CFLAGS += -DEFI_SUBSYSTEM=$(EFI_ARCH_SUBSYSTEM)
EFI_ARCH_LDFLAGS := --defsym=EFI_SUBSYSTEM=$(EFI_ARCH_SUBSYSTEM)
EFI_ARCH_FORMAT := -O binary
EFI_ARCH_SUFFIX := riscv64
EFI_ARCH_SUFFIX_UPPER := riscv64
EFI_ARCH_TIMESTAMP_LOCATION := 72
EFI_ARCH_HAVE_OBJCOPY := y

export EFI_ARCH_CCLDFLAGS EFI_ARCH_CFLAGS EFI_ARCH_CPPFLAGS EFI_ARCH_LDFLAGS
export EFI_ARCH_FORMAT EFI_ARCH_SUBSYSTEM EFI_ARCH_SUFFIX EFI_ARCH_SUFFIX_UPPER
export EFI_ARCH_TIMESTAMP_LOCATION EFI_ARCH_3264 EFI_ARCH_HAVE_OBJCOPY
endif
